kind: Pod
apiVersion: v1
metadata:
  name: banana-app
  labels:
    app: banana
spec:
  containers:
    - name: banana-app
      image: hashicorp/http-echo
      args:
        - -text=banana

---

kind: Service
apiVersion: v1
metadata:
  name: banana-service
spec:
  selector:
    app: banana
  ports:
    - port: 5678 # Default port for image

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banana-ingress
  # annotations:
    # cert-manager.io/cluster-issuer: le-prod
spec:
  ingressClassName: nginx
  rules:
  # - host: "test.test"
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: "/banana"
  #       backend:
  #         service:
  #           name: banana-service
  #           port:
  #             number: 5678
  - host: "aksgp.freemyip.com"
    http:
      paths:
      - pathType: Prefix
        path: "/banana"
        backend:
          service:
            name: banana-service
            port:
              number: 5678
  # tls:
  # - hosts:
  #   - pgossa.pro
  #   secretName: banana-one-cer

