kind: Pod
apiVersion: v1
metadata:
  name: cherry-app
  labels:
    app: cherry
spec:
  containers:
    - name: cherry-app
      image: hashicorp/http-echo
      args:
        - -text=cherry

---

kind: Service
apiVersion: v1
metadata:
  name: cherry-service
spec:
  selector:
    app: cherry
  ports:
    - port: 5678 # Default port for image

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cherry-ingress
  # annotations:
    # cert-manager.io/cluster-issuer: le-prod
spec:
  ingressClassName: nginx
  rules:
  # - host: "test.test"
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: "/cherry"
  #       backend:
  #         service:
  #           name: cherry-service
  #           port:
  #             number: 5678
  - host: "aksgp.freemyip.com"
    http:
      paths:
      - pathType: Prefix
        path: "/cherry"
        backend:
          service:
            name: cherry-service
            port:
              number: 5678
  # tls:
  # - hosts:
  #   - pgossa.pro
  #   secretName: cherry-one-cer


